### ISSUE TITLE
What if i want to use my own experimental data?

### ISSUE THREAD

**Issue by bengi000** [mueller-lab/EmbryoNet#14]
Hello! Professors,

I really appreciate your work on early detection of zebrafish embryo development, and I would like to use your project EmbryoNet for detection of potential development defects. But when it comes to load in FishLabeler, what kinds of data are right for input? when I navigated to the demo file folder, I realized that it contained not only time-lapse images, but also json files. So what should I do to generate such experiment files ? Now I only got images files of the embryos. Thanks in advance.

**Comment by hernanmorales-navarrete** [comment]
Hi @bengi000 

To use the FishLabeler, you first need to generate the segmentation bounding boxes and tracking for the embryo movies. You can do it using the FishClassifier. This will generate the json files that you need for the FishLabeler. Please, modify the settings in the FishClassifier according to your image data (you can see an example in the [Demo](https://github.com/mueller-lab/EmbryoNet/tree/main/Demo)). When opening the FishLabeler, you can use the json files generated in the folder "Classified_result_1_json_class_agnostic", which contains information only about the bounding boxes and tracking.

If you have further questions please contact us again.
