### ISSUE TITLE
Question about FishLabeler

### ISSUE THREAD

**Issue by Leondyw** [mueller-lab/EmbryoNet#15]
Dear Authors:
        After I use the GUI ,FishClassfier-GPU, I get three files. 
<img width="356" alt="屏幕截图 2024-02-21 205911" src="https://github.com/mueller-lab/EmbryoNet/assets/159577108/94f28439-64e5-45bb-bba1-491e0f5c85cf">
        They are like this .Which one should I use ? . And I have used all of them , why I got different consequence.
        I would appreciate brilliantly it if you can help me solve this problem . Have a good day! Thanks!

**Comment by hagorms** [comment]
Hello, Leondyw! 
Thank you for using our software. 

Classified_result_1_json_class_agnostic is a result generated and saved with only the default class (UNKNOWN). All embryos are labeled as unknowns. This dataset (json folder) is usually used for human labeling. 

EmbryoNet_GPU_classified_result_1_json is a folder with results before applying transition logic.  Every embryo is classified independently 8 times (4 90-degrees-rotations and 4 mirrored images of these rotations) and classifier uses majority vote to classify. 

EmbryoNet_GPU_classified_result_1_json_corrected uses the transition logic to "smooth" the EmbryoNet_GPU_classified_result_1_json. 

If you have any other questions, please re-open the issue. 
Best regards,
Matvey Safroshkin
