### ISSUE TITLE
How To Get The Class Activation Heatmaps

### ISSUE THREAD

**Issue by Leondyw** [mueller-lab/EmbryoNet#16]
Dear Authors,
        I really appreciate your work on early detection of zebrafish embryo development, and I would like to get the class activation heatmaps in the fig3 of your article 'EmbryoNet: using deep learning to link embryonic phenotypes to signaling pathways' . Is it the files in the folder "train_eval/model" . I try to creat the environment , but I got many problems , such as the version of python and others , it shows I can't get the proper version of the packpages ,how can I solve these . I would really appreciate it if you could help me get these . 

best regrads,
Leon

**Comment by hagorms** [comment]
Hello, Leon!
Could you please provide more information about this issue, about the system, add logs and errors or screenshots. 
Project works with python 3.8 
Please provide errors and screenshot for every step described here
https://github.com/mueller-lab/EmbryoNet/tree/main/Train_Eval 

Best regards,
Matvey

**Comment by Leondyw** [comment]
Dear Mr.hagorms!
        I try to use "generate_cam.py"  in  'EmbryoNet-main\Train_Eval\tools\GenerateVideos' . When I type 
```python 
python D:\EmbryoNet-main\EmbryoNet-main\Train_Eval\tools\GenerateVideos\generate_cam.py -f D:\EmbryoNet\byh_1-11_3h_0\qwe\images -mp D:\EmbryoNet-main\EmbryoNet-main\GUI\Default_Models\ZebraFish\bioImage_embryonet\EmbryoNet_GPU_batch_1.onnx -sp D:\heatmap 
```
 in the cmd , it turns out
```
File "D:\EmbryoNet-main\EmbryoNet-main\Train_Eval\tools\GenerateVideos\generate_cam.py", line 185, in <module>
    images = sorted(os.listdir(os.path.join(args.folder, full_path_to_image_folder)))
NotADirectoryError: [WinError 267] The directory name is invalid.: 'D:\\EmbryoNet\\byh_1-11_3h_0\\qwe\\images\\-B003--PO01--LO476--CO6--SL001--PX32500--PW0100--IN0100--TM280--X053545--Y033148--Z190000--T3328249152--WE00010.jpg'
```
I put all the images in the folder "D:\EmbryoNet\byh_1-11_3h_0\qwe\images" ,what should I do to solve this problem.And I also try to type "D:\EmbryoNet\byh_1-11_3h_0\qwe" and "D:\EmbryoNet\byh_1-11_3h_0" ,but they all don't work properly.
I would  appreciate it greatly if you can help me solve this . 
Best regards,
Leon

**Comment by hagorms** [comment]
Script tells you that you are giving the wrong path to the script.  Try giving -f D:\EmbryoNet\byh_1-11_3h_0\qwe  instead.
